# Generated by Django 5.1.5 on 2025-01-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('PG', 'Paying Guest'), ('FLAT', 'Flat'), ('HOSTEL', 'Hostel')], max_length=10)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gender_type', models.CharField(choices=[('M', 'Gents'), ('F', 'Ladies'), ('MX', 'Mixed')], max_length=2)),
                ('furnishing_type', models.CharField(blank=True, choices=[('FF', 'Fully Furnished'), ('SF', 'Semi Furnished'), ('NF', 'Non Furnished')], max_length=2, null=True)),
                ('bedroom_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bathroom_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bathroom_type', models.CharField(blank=True, choices=[('COMMON', 'Common Bathroom'), ('SINGLE', 'Attached Bathroom')], max_length=10, null=True)),
                ('persons_per_room', models.PositiveIntegerField(blank=True, null=True)),
                ('mess_included', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(to='properties.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyowner')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
