# Generated by Django 5.1.5 on 2025-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatProperty',
            fields=[
            ],
            options={
                'verbose_name': 'Flat Property',
                'verbose_name_plural': 'Flat Properties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='PGHostelProperty',
            fields=[
            ],
            options={
                'verbose_name': 'PG/Hostel Property',
                'verbose_name_plural': 'PG/Hostel Properties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.property',),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
