# Generated by Django 5.1.5 on 2025-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertylocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyLocation',
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
