# Generated by Django 5.1.5 on 2025-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_mess_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='mess_included',
            field=models.BooleanField(default=False),
        ),
    ]
