# Generated by Django 5.1.5 on 2025-02-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_mess_messmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='breakfast',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='dinner',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='lunch',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='snacks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
