# Generated by Django 5.1.5 on 2025-02-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_messmenu_breakfast_alter_messmenu_dinner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mess',
            options={'verbose_name_plural': 'Messes'},
        ),
        migrations.AddField(
            model_name='mess',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mess',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
