# Generated by Django 5.1.5 on 2025-02-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_mess_options_mess_latitude_mess_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mess',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
