# Generated by Django 5.1.5 on 2025-02-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_mess_contact_mess_daily_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess',
            old_name='contact',
            new_name='contact_number',
        ),
    ]
