# Generated by Django 5.1.5 on 2025-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_messmenu_snacks_messmenu_snacks_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messmenu',
            name='snacks_available',
        ),
    ]
