# Generated by Django 5.1.5 on 2025-02-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_messmenu_snacks_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='is_snacks_available',
            field=models.BooleanField(default=False),
        ),
    ]
